name: Validate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    name: With hassfest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v2

      - name: ✅ Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

  validate-hacs:
    runs-on: ubuntu-latest
    name: With HACS Action
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v2

      - name: ✅ HACS validation
        uses: hacs/action@main
        with:
          category: integration
          comment: false
          ignore: brands wheels